# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20180918_1949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
