# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOPInstanceUID', models.CharField(max_length=200)),
                ('SOPClassUID', models.CharField(max_length=100)),
                ('ImageType', models.CharField(max_length=100)),
                ('PhotometricInterpretation', models.CharField(max_length=20, null=True)),
                ('RescaleSlope', models.IntegerField()),
                ('RescaleIntercept', models.IntegerField()),
                ('SliceLocation', models.IntegerField()),
                ('PixelSpacing', models.CharField(max_length=50)),
                ('ImageOrientationPatient', models.CharField(max_length=100)),
                ('ImagePositionPatient', models.CharField(max_length=100)),
                ('SliceThickness', models.CharField(max_length=100)),
                ('BodypartExamined', models.CharField(max_length=100, null=True)),
                ('Rows', models.IntegerField()),
                ('Columns', models.IntegerField()),
            ],
            options={
                'db_table': 'ct_images',
            },
        ),
        migrations.CreateModel(
            name='OVH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binValue', models.TextField(null=True)),
                ('binAmount', models.TextField(null=True)),
                ('OverlapArea', models.IntegerField(null=True)),
                ('ptv_id', models.IntegerField(null=True)),
                ('OAR_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ovh',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=200)),
                ('BirthDate', models.DateField(null=True)),
                ('Gender', models.CharField(max_length=20, null=True)),
                ('EnthicGroup', models.CharField(max_length=200, null=True)),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='ROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROIName', models.CharField(max_length=100, unique=True)),
                ('ROIDisplayColor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'oar_dictionary',
            },
        ),
        migrations.CreateModel(
            name='RTContour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContourGeometricType', models.CharField(max_length=100)),
                ('NumberOfContourPoints', models.IntegerField()),
                ('ContourData', models.TextField()),
                ('ReferencedSOPClassUID', models.CharField(max_length=100)),
                ('ReferencedSOPInstanceUID', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rt_contour',
            },
        ),
        migrations.CreateModel(
            name='RTDose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOPClassUID', models.CharField(max_length=100)),
                ('SOPInstanceUID', models.CharField(max_length=100)),
                ('DoseGridScaling', models.CharField(max_length=100)),
                ('DoseSummationType', models.CharField(max_length=100, null=True)),
                ('DoseType', models.CharField(max_length=100, null=True)),
                ('DoseUnits', models.CharField(max_length=100, null=True)),
                ('ReferencedRTPlanSequence', models.CharField(max_length=100)),
                ('ReferencedStructureSetSequence', models.CharField(max_length=100)),
                ('fk_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Patient')),
            ],
            options={
                'db_table': 'rt_dose',
            },
        ),
        migrations.CreateModel(
            name='RTDoseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Columns', models.IntegerField()),
                ('Rows', models.IntegerField()),
                ('ImageOrientationPatient', models.CharField(max_length=20)),
                ('ImagePositionPatient', models.CharField(max_length=20)),
                ('PhotometricInterpretation', models.CharField(max_length=20, null=True)),
                ('PixelSpacing', models.CharField(max_length=20)),
                ('NumberOfFrames', models.IntegerField()),
                ('ImageData', models.TextField()),
                ('fk_dose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.RTDose')),
                ('fk_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Patient')),
            ],
            options={
                'db_table': 'rt_dose_image',
            },
        ),
        migrations.CreateModel(
            name='RTDVH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DVHDoseScaling', models.CharField(max_length=20)),
                ('DVHMaximumDose', models.FloatField()),
                ('DVHMeanDose', models.FloatField()),
                ('DVHMinimumDose', models.FloatField()),
                ('DVHNumberOfBins', models.IntegerField()),
                ('DVHReferencedROI', models.CharField(max_length=10)),
                ('DVHType', models.CharField(max_length=10, null=True)),
                ('DVHVolumeUnits', models.CharField(max_length=10)),
                ('DoseType', models.CharField(max_length=10)),
                ('DoseUnits', models.CharField(max_length=10)),
                ('DVHData', models.TextField()),
                ('fk_dose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.RTDose')),
                ('fk_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Patient')),
            ],
            options={
                'db_table': 'rt_dvh',
            },
        ),
        migrations.CreateModel(
            name='RTIsDose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RowPosition', models.TextField()),
                ('ColumnPosition', models.TextField()),
                ('IsDoseValue', models.IntegerField()),
                ('fk_ct_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.CTImages')),
                ('fk_dose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.RTDose')),
                ('fk_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Patient')),
            ],
            options={
                'db_table': 'rt_isdose',
            },
        ),
        migrations.CreateModel(
            name='RTROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROIName', models.CharField(max_length=100)),
                ('Volume', models.FloatField()),
                ('TotalContours', models.IntegerField()),
                ('ROINumber', models.CharField(max_length=200, null=True)),
                ('fk_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Patient')),
            ],
            options={
                'db_table': 'rt_rois',
            },
        ),
        migrations.CreateModel(
            name='RTStructureSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOPInstanceUID', models.CharField(max_length=200)),
                ('SOPClassUID', models.CharField(max_length=100)),
                ('TotalROIs', models.IntegerField()),
                ('fk_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Patient')),
            ],
            options={
                'db_table': 'rt_structureset',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeriesInstanceUID', models.CharField(max_length=200)),
                ('SeriesDate', models.DateField(null=True)),
                ('SeriesDescription', models.CharField(max_length=200, null=True)),
                ('SeriesType', models.CharField(max_length=100)),
                ('Modality', models.CharField(max_length=100)),
                ('SeriesNumber', models.CharField(max_length=100, null=True)),
                ('PhysicianOfRecord', models.CharField(max_length=100, null=True)),
                ('Manufacturer', models.CharField(max_length=50, null=True)),
                ('fk_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Patient')),
            ],
            options={
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBStudyID', models.CharField(max_length=100)),
                ('Similarity', models.FloatField(max_length=200)),
                ('OVHDisimilarity', models.FloatField(max_length=200)),
                ('STSDisimilarity', models.FloatField(max_length=200)),
                ('TargetOAR', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'similarity',
            },
        ),
        migrations.CreateModel(
            name='STS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation_bins', models.TextField(null=True)),
                ('distance_bins', models.TextField(null=True)),
                ('azimuth_bins', models.TextField(null=True)),
                ('amounts', models.TextField(null=True)),
                ('ptv_id', models.IntegerField(null=True)),
                ('OAR_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sts',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudyInstanceUID', models.CharField(max_length=200)),
                ('StudyDate', models.DateField(null=True)),
                ('StudyDescription', models.CharField(max_length=200, null=True)),
                ('TotalSeries', models.IntegerField()),
                ('fk_patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Patient')),
                ('fk_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'studies',
            },
        ),
        migrations.AddField(
            model_name='sts',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='similarity',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='series',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='series',
            name='fk_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rtstructureset',
            name='fk_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Series'),
        ),
        migrations.AddField(
            model_name='rtstructureset',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='rtstructureset',
            name='fk_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rtroi',
            name='fk_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Series'),
        ),
        migrations.AddField(
            model_name='rtroi',
            name='fk_structureset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.RTStructureSet'),
        ),
        migrations.AddField(
            model_name='rtroi',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='rtroi',
            name='fk_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rtisdose',
            name='fk_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Series'),
        ),
        migrations.AddField(
            model_name='rtisdose',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='rtdvh',
            name='fk_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Series'),
        ),
        migrations.AddField(
            model_name='rtdvh',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='rtdvh',
            name='fk_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rtdoseimage',
            name='fk_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Series'),
        ),
        migrations.AddField(
            model_name='rtdoseimage',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='rtdoseimage',
            name='fk_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rtdose',
            name='fk_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Series'),
        ),
        migrations.AddField(
            model_name='rtdose',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='rtdose',
            name='fk_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rtcontour',
            name='fk_roi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.RTROI'),
        ),
        migrations.AddField(
            model_name='rtcontour',
            name='fk_structureset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.RTStructureSet'),
        ),
        migrations.AddField(
            model_name='ovh',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='ctimages',
            name='fk_patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Patient'),
        ),
        migrations.AddField(
            model_name='ctimages',
            name='fk_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Series'),
        ),
        migrations.AddField(
            model_name='ctimages',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
        migrations.AddField(
            model_name='ctimages',
            name='fk_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
