# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovh',
            name='fk_study_id',
        ),
        migrations.RemoveField(
            model_name='sts',
            name='fk_study_id',
        ),
        migrations.DeleteModel(
            name='OVH',
        ),
        migrations.DeleteModel(
            name='STS',
        ),
    ]
