# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 23:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtroi',
            name='fk_patient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtroi',
            name='fk_series_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.Series'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtroi',
            name='fk_study_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtroi',
            name='fk_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
