# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-05 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtroi',
            name='ROIName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.ROI'),
        ),
    ]
