# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20171118_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binValue', models.TextField(null=True)),
                ('binAmount', models.TextField(null=True)),
                ('OverlapArea', models.IntegerField(null=True)),
                ('ptv_id', models.IntegerField(null=True)),
                ('OAR_id', models.IntegerField(null=True)),
                ('fk_study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study')),
            ],
            options={
                'db_table': 'ovh',
            },
        ),
        migrations.CreateModel(
            name='STS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation_bins', models.TextField(null=True)),
                ('distance_bins', models.TextField(null=True)),
                ('azimuth_bins', models.TextField(null=True)),
                ('amounts', models.TextField(null=True)),
                ('ptv_id', models.IntegerField(null=True)),
                ('OAR_id', models.IntegerField(null=True)),
                ('fk_study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study')),
            ],
            options={
                'db_table': 'sts',
            },
        ),
    ]
