# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20171108_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctimages',
            name='BodypartExamined',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
