# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20171110_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='OVH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XValues', models.TextField(null=True)),
                ('YValues', models.TextField()),
                ('OverlapArea', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ovh',
            },
        ),
        migrations.CreateModel(
            name='ROI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROIName', models.CharField(max_length=100, unique=True)),
                ('ROIDisplayColor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'oar_dictionary',
            },
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DBStudyID', models.CharField(max_length=100)),
                ('Similarity', models.FloatField(max_length=200)),
                ('OVHDisimilarity', models.FloatField(max_length=200)),
                ('STSDisimilarity', models.FloatField(max_length=200)),
                ('TargetOAR', models.CharField(max_length=200)),
                ('fk_study_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study')),
            ],
            options={
                'db_table': 'similarity',
            },
        ),
        migrations.CreateModel(
            name='STS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.ROI')),
            ],
            options={
                'db_table': 'sts',
            },
        ),
        migrations.RenameField(
            model_name='rtroi',
            old_name='ROIDisplayColor',
            new_name='ROIType',
        ),
        migrations.RemoveField(
            model_name='rtroi',
            name='ROIName',
        ),
        migrations.RemoveField(
            model_name='rtroi',
            name='ROINumber',
        ),
        migrations.AddField(
            model_name='ovh',
            name='OAR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.ROI'),
        ),
        migrations.AddField(
            model_name='ovh',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
    ]
