# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-18 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20180918_1949'),
        ('upload', '0003_ovh_sts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTIsoDose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RowPosition', models.TextField()),
                ('ColumnPosition', models.TextField()),
                ('IsDoseValue', models.IntegerField()),
            ],
            options={
                'db_table': 'rt_isodose',
            },
        ),
        migrations.RemoveField(
            model_name='rtisdose',
            name='fk_ct_image_id',
        ),
        migrations.RemoveField(
            model_name='rtisdose',
            name='fk_dose_id',
        ),
        migrations.RemoveField(
            model_name='rtisdose',
            name='fk_patient_id',
        ),
        migrations.RemoveField(
            model_name='rtisdose',
            name='fk_series_id',
        ),
        migrations.RemoveField(
            model_name='rtisdose',
            name='fk_study_id',
        ),
        migrations.RemoveField(
            model_name='ctimages',
            name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='ovh',
            name='OAR_id',
        ),
        migrations.RemoveField(
            model_name='ovh',
            name='binAmount',
        ),
        migrations.RemoveField(
            model_name='ovh',
            name='binValue',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='EnthicGroup',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='rtdose',
            name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='rtdoseimage',
            name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='rtdvh',
            name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='rtroi',
            name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='rtstructureset',
            name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='series',
            name='fk_user_id',
        ),
        migrations.RemoveField(
            model_name='sts',
            name='OAR_id',
        ),
        migrations.RemoveField(
            model_name='study',
            name='fk_user_id',
        ),
        migrations.AddField(
            model_name='ovh',
            name='bin_amount',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ovh',
            name='bin_value',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ovh',
            name='oar_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='EthnicGroup',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fk_hospital_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.Hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sts',
            name='oar_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='RTIsDose',
        ),
        migrations.AddField(
            model_name='rtisodose',
            name='fk_ct_image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.CTImages'),
        ),
        migrations.AddField(
            model_name='rtisodose',
            name='fk_dose_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.RTDose'),
        ),
        migrations.AddField(
            model_name='rtisodose',
            name='fk_patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Patient'),
        ),
        migrations.AddField(
            model_name='rtisodose',
            name='fk_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Series'),
        ),
        migrations.AddField(
            model_name='rtisodose',
            name='fk_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Study'),
        ),
    ]
